FROM node:22-alpine as builder
WORKDIR /app

COPY package-lock.json .
COPY package.json .
RUN npm ci --include=optional
COPY . .
RUN npm run build

FROM node:22-alpine as runner
WORKDIR /app

COPY --from=builder /app/package.json .
COPY --from=builder /app/package-lock.json .
COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]