version: "3.8"

services:
  chatin-web:
    build:
      context: .
      dockerfile: dockerfile
      target: runner
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  postgres:
    container_name: container-pg
    image: ankane/pgvector
    hostname: localhost
    ports:
      - "5435:5432" # host:container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_TRUST_LOCALNET: true
      POSTGRES_TRUST_LOCALNET: true
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  postgres-data:
